// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Shield.62df6510-15e7-4df5-8fbb-fc5f39b8545f";
        public const string Name = "ShieldVSExtension";
        public const string Description = @"Advanced obfuscator for .NET apps. Protect your brand, secure code & data. Compatible with .NET, Xamarin, UWP, .NET Core, .NET Standard, .NET MAUI, .NET 5, .NET 6 & .NET 7. Easily integrates into Visual Studio compilation process.";
        public const string Language = "en-US";
        public const string Version = "2.0.0.7";
        public const string Author = "ByteHide";
        public const string Tags = "security, source, vulnerabilities, code, obfuscation, obfuscator, code security, code protection, protection, data protection, encryption, analysis";
    }
}
