// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VS22Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS22Extension.4cc8e35f-f139-47e0-b300-b845a4f0a0d6";
        public const string Name = "VS22Extension";
        public const string Description = @"Advanced obfuscator for .NET apps. Protect your brand, secure code & data. Compatible with .NET, Xamarin, UWP, .NET Core, .NET Standard, .NET MAUI, .NET 5, .NET 6 & .NET 7. Easily integrates into Visual Studio compilation process.";
        public const string Language = "en-US";
        public const string Version = "2.0.0.6";
        public const string Author = "ByteHide";
        public const string Tags = "security, source, vulnerabilities, code, obfuscation, obfuscator, code security, code protection, protection, data protection, encryption, analysis";
    }
}
