// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VS22Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS22Extension.4cc8e35f-f139-47e0-b300-b845a4f0a0d6";
        public const string Name = "VS22Extension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Juan Alberto Espana";
        public const string Tags = "";
    }
}
